version: '3.8'

services:
  backend:
    build:
      context: ./crewai_backend
    container_name: logistics_backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
      - OPENAI_API_KEY=${OPENAI_API_KEY:-sk-fake-key-for-demo}

  frontend:
    build:
      context: ./frontend
    container_name: logistics_frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://backend:8000
